version: "3"
services:
  php:
    container_name: php
    restart: always
    build: ./services/php
    volumes:
      - ./services/php:/usr/local/etc/php
      - ./src:/var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
    depends_on:
      - mysql
      - redis
  worker:
    container_name: worker
    build: ./services/php
    volumes:
      - ./src:/var/www/html
      - ./services/php:/usr/local/etc/php
    command: php artisan horizon
    depends_on:
      - redis
      - php
  mysql:
    container_name: mysql
    restart: always
    build: ./services/mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./services/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_USER: laravel
      MYSQL_DATABASE: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: laravel
  redis:
    container_name: redis
    restart: always
    build: ./services/redis
    volumes:
      - ./data/redis:/data
      - ./services/redis:/usr/local/etc/redis
    command:
      - /usr/local/etc/redis/redis.conf
  nginx:
    container_name: nginx
    restart: always
    build: ./services/nginx
    #command: "/bin/sh -c 'while :; do sleep 6h; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./services/nginx:/etc/nginx
      - ./data/letsencrypt/certs:/etc/letsencrypt
      - ./data/letsencrypt/certs-data:/data/letsencrypt
    depends_on:
      - mysql
      - redis
      - php
  certbot:
    container_name: certbot
    image: certbot/certbot
    #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done;'"
    depends_on:
      - nginx
    volumes:
      - ./data/letsencrypt:/data/letsencrypt